services:
  - type: web
    name: sideout-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn vb_roster.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sideout-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

databases:
  - name: sideout-db